services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_1_URL: db-1
      DB_2_URL: db-2
      DB_3_URL: db-3
    depends_on:
      - migrate

  db-1:
    image: postgres:17
    container_name: db-1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: shard1
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user1", "-d", "shard1"]
      interval: 10s
      retries: 5

  db-2:
    image: postgres:17
    container_name: db-2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: shard2
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user2", "-d", "shard2"]
      interval: 10s
      retries: 5

  db-3:
    image: postgres:17
    container_name: db-3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: shard3
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user3", "-d", "shard3"]
      interval: 10s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    environment:
      DB_1_URL: db-1
      DB_2_URL: db-2
      DB_3_URL: db-3
    depends_on:
      db-1:
        condition: service_healthy
      db-2:
        condition: service_healthy
      db-3:
        condition: service_healthy
    command: ["python", "migrate.py"]
